// angular-blog/src/app/header/header.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { DOCUMENT } from '@angular/common';
import { BackendService } from '../backend.service';

interface Option {
  platform: string;
  technique: string;
  url: string;
}

@Component({
  // tslint:disable-next-line:component-selector
  selector: '[app-header]',
  templateUrl: './header.component.html'
})
export class HeaderComponent implements OnInit {

  options: Option[];

  constructor(private http: HttpClient,
              private router: Router,
              @Inject(DOCUMENT) private document: Document,
              private backendService: BackendService) {
  }

  ngOnInit(): void {
    this.http.get(`${this.backendService.getBaseURL()}/options`).subscribe((options: any) => this.options = options);
  }

  getPageURL(optionUrl: string) {
    return `${optionUrl}${this.router.url}`;
  }

  isActive(option: Option) {
    const url = new URL(option.url);
    return url.protocol === this.document.location.protocol &&
      url.hostname === this.document.location.hostname &&
      url.port === this.document.location.port;
  }

  onSelectChanged(url: string) {
    window.location.href = this.getPageURL(url);
  }

  onClickMenu() {
    this.document.body.classList.toggle('menu-open');
  }
}

<div class="header-content">
  <button class="toggle-menu" (click)="onClickMenu()"></button>
  <h3>Rendering Strategies for Web Apps</h3>
  <select (change)="onSelectChanged($event.target.value)">
    <option *ngFor="let option of options" [value]="option.url" [selected]="isActive(option)">
      {{option.platform}}:{{option.technique}}</option>
  </select>
</div>

// vue-blog/src/components/Header.vue
<template>
  <section class="page-header">
    <div class="header-content">
      <button class="toggle-menu" v-on:click="onClickMenu"></button>
      <h3>Rendering Strategies for Web Apps</h3>
      <select v-on:change="onSelectChanged">
        <option v-for="option of options" v-bind:key="option.url" v-bind:value="option.url" v-bind:selected="isActive(option)">
          {{option.platform}}:{{option.technique}}
        </option>
      </select>
    </div>
  </section>
</template>

<script>
  import {getOptions} from '../util/data.util';

  export default {
    name: 'Header',
    data() {
      return {
        options: []
      }
    },
    created() {
      this.fetchData();
    },
    methods: {
      async fetchData() {
        this.options = await getOptions();
      },
      isActive(option) {
        const location = document.location;
        const url = new URL(option.url);
        return url.protocol === location.protocol &&
          url.hostname === location.hostname &&
          url.port === location.port;
      },
      onClickMenu() {
        document.body.classList.toggle('menu-open');
      },
      onSelectChanged(event) {
        window.location.href = `${event.target.value}${this.$route.path}`
      }
    }
  }
</script>
