// react-blog/src/PostList.js
import React, {useEffect, useState} from 'react';
import {
  Link,
  useLocation
} from 'react-router-dom';
import {getToc} from './util/data.util';

export function PostList(props) {

  const [posts, setPosts] = useState(props.toc || []);
  const location = useLocation();

  useEffect(() => {
    if (!posts.length) {
      getToc()
        .then(data => setPosts(data));
    }
  }, [posts.length]);

  function getActiveClass(post) {
    return !!location.pathname.split('#')[0].split('/').find(p => post.path === p) ? 'active' : '';
  }

  return <ul className="post-list">
    {
      posts.map((post, index) =>
        <li className={getActiveClass(post)} key={index}>
          <Link to={`/posts/${post.path}`}>{post.title}</Link>
          {
            post.children && <ul>
              {
                post.children.map((child, childIndex) =>
                  <li className={getActiveClass(child)} key={childIndex}>
                  <Link to={`/posts/${child.path}`}>{child.title}</Link>
                </li>)
              }
            </ul>
          }
        </li>
      )
    }
  </ul>
};

// vue-blog/src/components/PostList.vue
<template>
  <ul class="post-list">
      <router-link
        v-for="post of posts" v-bind:key="post.path"
        v-bind:to="post.path"
        v-slot="{ href, route, navigate, isActive }">
        <li :class="[isActive && 'active']"><a :href="href" @click="navigate">{{ post.title }}</a></li>
        <ul v-if="post.children">
          <router-link
            v-for="child of post.children" v-bind:key="child.path"
            v-bind:to="child.path"
            v-slot="{ href, route, navigate, isActive }">
            <li :class="[isActive && 'active']"><a :href="href" @click="navigate">{{ child.title }}</a></li>
          </router-link>
        </ul>
      </router-link>
  </ul>
</template>

<script>
  import {getToc} from '../util/data.util';

  export default {
    name: 'PostList',
    data() {
      return {
        posts: []
      }
    },
    mounted() {
      if (!this.posts.length) {
        this.fetchData();
      }
    },
    async serverPrefetch() {
      await this.fetchData();
    },
    methods: {
      async fetchData() {
        this.posts = await getToc();
      }
    }
  }
</script>
