// react-blog/src/Post.js
import React, {useEffect, useState, useRef} from 'react';
import {
  useParams,
  useHistory
} from 'react-router-dom';
import {getPost} from './util/data.util';

function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
}

export function Post(props) {

  const [content, setContent] = useState(props.content);
  const { id } = useParams();
  const previousId = usePrevious(id);
  const history = useHistory();

  useEffect(() => {
    if (!content || (previousId && id !== previousId)) {
      getPost(id)
        .then(data => {
          document.scrollingElement.scrollTop = 0;
          setContent(data);
        });
    }
  }, [ id, content, previousId ]);

  function onClick(event) {
    const href = event.target.getAttribute('href');
    if (href && !(href.startsWith('http')) && !(href.startsWith('#'))) {
      history.push(href);
      event.preventDefault();
    }
  }

  return <div className="post" dangerouslySetInnerHTML={{__html: content}} onClick={event => onClick(event)}></div>;
}

// vue-blog/src/components/Post.vue
<template>
  <div class="post" v-html="content" v-on:click="clickPost">
  </div>
</template>

<script>
  import {getPost, getPostFromCache} from '../util/data.util';
  import {isBrowser} from '../util/env.util';

  export default {
    name: 'Post',
    data() {
      return {
        content: getPostFromCache(this.$route.params.id)
      }
    },
    mounted() {
      this.setMeta(this.$route.params.id);
      this.fetchData(this.$route.params.id);
    },
    beforeRouteUpdate(to, from, next) {
      document.scrollingElement.scrollTop = 0;
      this.setMeta(to.params.id);
      this.fetchData(to.params.id);
      next();
    },
    async serverPrefetch() {
      this.setMeta(this.$route.params.id);
      await this.fetchData(this.$route.params.id);
    },
    methods: {
      async fetchData(id) {
        this.content = await getPost(id);
      },
      setMeta(title) {
        if (isBrowser()) {
          document.title = title;
          document.head.querySelector('meta[name="og:title"]').setAttribute('value', title);
        }
      },
      clickPost(event) {
        const href = event.target.getAttribute('href');
        if (href) {
          if (href.startsWith('http') || href.startsWith('#')) {
            return;
          } else {
            this.$router.push((href));
            event.preventDefault();
          }
        }
      }
    }
  }
</script>
