// vue-blog/src/App.vue
<template>
  <div id="app">
    <Header></Header>
    <section class="page-menu" v-on:click="onClickMenu">
      <PostList></PostList>
    </section>
    <section class="page-content">
      <router-view></router-view>
    </section>
  </div>
</template>

<script>
  import PostList from './components/PostList';
  import Header from './components/Header';

  export default {
    name: 'App',
    components: {Header, PostList},
    methods: {
      onClickMenu() {
        document.body.classList.remove('menu-open');
      }
    }
  }
</script>

// angular-blog/src/app/app.component.ts
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-blog';

  constructor(@Inject(DOCUMENT) private document: Document) {
  }

  onClickMenu() {
    this.document.body.classList.remove('menu-open');
  }
}
