// react-blog/src/PostList.js
import React, {useEffect, useState} from 'react';
import {
  Link,
  useLocation
} from 'react-router-dom';

export function PostList() {

  const [posts, setPosts] = useState([]);
  const location = useLocation();

  useEffect(() => {
    fetch(`http://localhost:8082/posts/toc.json`)
      .then(response => response.json())
      .then(data => setPosts(data));
  }, []);

  function getActiveClass(post) {
    return !!location.pathname.split('#')[0].split('/').find(p => post.path === p) ? 'active' : '';
  }

  return <ul className="post-list">
    <li><Link to="/">Home</Link></li>
    {
      posts.map((post, index) =>
        <li className={getActiveClass(post)} key={index}>
          <Link to={`/posts/${post.path}`}>{post.title}</Link>
          {
            post.children && <ul>
              {
                post.children.map((child, childIndex) =>
                  <li className={getActiveClass(child)} key={childIndex}>
                  <Link to={`/posts/${child.path}`}>{child.title}</Link>
                </li>)
              }
            </ul>
          }
        </li>
      )
    }
  </ul>
};

// src/app/post-list/post-list.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BACKEND_BASE_URL } from '../config';
import { ActivatedRoute, Router } from '@angular/router';

interface Post {
  title: string;
  path: string;
  children?: Post[];
}

@Component({
  selector: 'app-post-list',
  templateUrl: './post-list.component.html'
})
export class PostListComponent implements OnInit {
  posts: Post[];

  constructor(private http: HttpClient,
              private route: ActivatedRoute,
              private router: Router,
              @Inject(BACKEND_BASE_URL) private baseUrl: string) {
  }

  ngOnInit() {
    this.http.get(`${this.baseUrl}/posts/toc.json`)
      .subscribe((data: Post[]) => this.posts = data);
  }

  isActive(post: Post): boolean {
    return !!this.router.url.split('#')[0].split('/').find(p => post.path === p);
  }
}

<ul class="post-list">
  <li><a [routerLink]="['/']">Home</a></li>
  <li *ngFor="let post of posts" [class.active]="isActive(post)">
    <a [routerLink]="['posts/' + post.path]">{{post.title}}</a>
    <ul *ngIf="post.children">
      <li *ngFor="let child of post.children" [class.active]="isActive(child)">
        <a [routerLink]="['posts/' + child.path]">{{child.title}}</a>
    </ul>
  </li>
</ul>
